// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsJnRiap_5k5NgUv3H1sxZlvCr28lpy1Q',
    appId: '1:422837476423:web:5590cb552e6ac13af1e562',
    messagingSenderId: '422837476423',
    projectId: 'chat-app-f57ed',
    authDomain: 'chat-app-f57ed.firebaseapp.com',
    storageBucket: 'chat-app-f57ed.appspot.com',
    measurementId: 'G-4ZYH2ZYM3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0i_lKuOznRsKxQ6d7qsWFnxjf67FSJRI',
    appId: '1:422837476423:android:b129ae2bb67efb9cf1e562',
    messagingSenderId: '422837476423',
    projectId: 'chat-app-f57ed',
    storageBucket: 'chat-app-f57ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBoX1IFrZ8tyx6Gq0Wcq5RS4otLuDbTj0',
    appId: '1:422837476423:ios:219defdf3b33c635f1e562',
    messagingSenderId: '422837476423',
    projectId: 'chat-app-f57ed',
    storageBucket: 'chat-app-f57ed.appspot.com',
    iosClientId: '422837476423-6f3p2nor073sisp27tgur092kckv085i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBoX1IFrZ8tyx6Gq0Wcq5RS4otLuDbTj0',
    appId: '1:422837476423:ios:219defdf3b33c635f1e562',
    messagingSenderId: '422837476423',
    projectId: 'chat-app-f57ed',
    storageBucket: 'chat-app-f57ed.appspot.com',
    iosClientId: '422837476423-6f3p2nor073sisp27tgur092kckv085i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
